<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FacilitiesTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('facilities')->insert([
            // === MAIN FACILITIES ===
            [
                'name' => 'Library',
                'category' => 'Educational',
                'department' => 'Academics',
                'description' => 'A place where students can study and access academic resources.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gymnasium',
                'category' => 'Sports',
                'department' => 'Physical Education',
                'description' => 'Indoor facility for sports events and student activities.',
                'hours' => '6:00 AM - 9:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cafeteria',
                'category' => 'Food & Beverage',
                'department' => 'Student Services',
                'description' => 'Serves meals and refreshments for students and staff.',
                'hours' => '7:00 AM - 7:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Computer Laboratory',
                'category' => 'Technology',
                'department' => 'College of Computing and Information Sciences',
                'description' => 'Lab equipped with computers and internet access for IT-related courses.',
                'hours' => '8:00 AM - 6:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Science Laboratory',
                'category' => 'Educational',
                'department' => 'College of Agriculture and Natural Resources',
                'description' => 'Facility for scientific and agricultural research experiments.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Auditorium',
                'category' => 'Event',
                'department' => 'Administration',
                'description' => 'Used for assemblies, conferences, and cultural programs.',
                'hours' => '8:00 AM - 9:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === ACADEMIC BUILDINGS / COLLEGES ===
            [
                'name' => 'College of Agriculture and Natural Resources (CANR)',
                'category' => 'Academic Building',
                'department' => 'Agriculture',
                'description' => 'Main college for agriculture, agronomy, and related studies.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'College of Computing and Information Sciences (CCIS)',
                'category' => 'Academic Building',
                'department' => 'Computing and Information Sciences',
                'description' => 'Home of IT and computer science programs with modern labs.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'College of Teacher Education (CTE)',
                'category' => 'Academic Building',
                'department' => 'Education',
                'description' => 'Building dedicated to training future educators and researchers.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'College of Arts and Sciences (CAS)',
                'category' => 'Academic Building',
                'department' => 'Arts and Sciences',
                'description' => 'Building for general education and liberal arts programs.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'College of Business Administration (CBA)',
                'category' => 'Academic Building',
                'department' => 'Business Administration',
                'description' => 'Provides education in business, management, and entrepreneurship.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'College of Engineering and Industrial Technology (CEIT)',
                'category' => 'Academic Building',
                'department' => 'Engineering and Industrial Technology',
                'description' => 'Houses mechanical, civil, and electrical engineering programs.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === OFFICES AND ADMIN UNITS ===
            [
                'name' => 'Office of the President',
                'category' => 'Administration',
                'department' => 'Executive',
                'description' => 'Central office for university leadership and management.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Office of the Vice President for Academic Affairs',
                'category' => 'Administration',
                'department' => 'Academic Affairs',
                'description' => 'Oversees curriculum and academic development.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Office of Student Affairs and Services',
                'category' => 'Student Support',
                'department' => 'Student Services',
                'description' => 'Handles student guidance, welfare, and scholarship services.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Digital Transformation Center',
                'category' => 'Technology',
                'department' => 'IT Services',
                'description' => 'Leads campus digitalization and ICT modernization projects.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Registrar’s Office',
                'category' => 'Academic Services',
                'department' => 'Registrar',
                'description' => 'Maintains academic records and student enrollment data.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Finance Office',
                'category' => 'Administration',
                'department' => 'Finance',
                'description' => 'Responsible for budgeting, accounting, and disbursement of funds.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Research, Extension, and Training Office',
                'category' => 'Research',
                'department' => 'Research and Development',
                'description' => 'Facilitates research and community outreach programs.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Guidance and Counseling Office',
                'category' => 'Student Support',
                'department' => 'Guidance Office',
                'description' => 'Provides psychological support and career guidance to students.',
                'hours' => '8:00 AM - 4:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Health Services Center',
                'category' => 'Medical',
                'department' => 'Student Health',
                'description' => 'Provides first aid and medical consultations for the campus community.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Registrar and Records Building',
                'category' => 'Administration',
                'department' => 'Registrar',
                'description' => 'Handles documentation and issuance of academic credentials.',
                'hours' => '8:00 AM - 5:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === CAMPUS UTILITIES ===
            [
                'name' => 'Dormitory',
                'category' => 'Accommodation',
                'department' => 'Student Housing',
                'description' => 'Provides lodging for students and visiting faculty.',
                'hours' => '24/7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Basketball Court',
                'category' => 'Sports',
                'department' => 'Physical Education',
                'description' => 'Outdoor court for recreational sports and PE classes.',
                'hours' => '6:00 AM - 9:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Covered Court',
                'category' => 'Sports',
                'department' => 'Physical Education',
                'description' => 'Multi-purpose covered area for sports and assemblies.',
                'hours' => '6:00 AM - 9:00 PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
